/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Assignments;

import Assignment_11.Assignment_11_GUI;

/**
 *
 * @author Dave
 */
public class Asgn_0_MainMenu extends javax.swing.JFrame {

  /**
   * Creates new form MainMenu
   */
  public Asgn_0_MainMenu() {
    initComponents();
    this.setLocationRelativeTo(null); // center JFrame on screen;
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_1_NumberAddition = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        m_btnHelloWorld = new javax.swing.JButton();
        m_btnHelloWorldMe = new javax.swing.JButton();
        btn_Polymorphism = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Programming 2 - Main Menu");

        btn_1_NumberAddition.setText("1 - Number Addition");
        btn_1_NumberAddition.setToolTipText("Assignment 1 - Number Addition");
        btn_1_NumberAddition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1_NumberAdditionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Select an Assignment to view.");

        m_btnHelloWorld.setText("3 - Say Hello");
        m_btnHelloWorld.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnHelloWorldActionPerformed(evt);
            }
        });

        m_btnHelloWorldMe.setText("3 - Hello World (Me)");
        m_btnHelloWorldMe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_btnHelloWorldMeActionPerformed(evt);
            }
        });

        btn_Polymorphism.setText("11 - Polymorphism");
        btn_Polymorphism.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PolymorphismActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 162, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(m_btnHelloWorld, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_1_NumberAddition, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_Polymorphism)
                            .addComponent(m_btnHelloWorldMe))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_1_NumberAddition)
                    .addComponent(m_btnHelloWorldMe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(m_btnHelloWorld)
                .addGap(29, 29, 29)
                .addComponent(btn_Polymorphism)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void btn_1_NumberAdditionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1_NumberAdditionActionPerformed
    Asgn_1_NumberAdditionUI naf = new Asgn_1_NumberAdditionUI();
    naf.setLocationRelativeTo(null);
    naf.setVisible(true);
  }//GEN-LAST:event_btn_1_NumberAdditionActionPerformed

    private void m_btnHelloWorldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnHelloWorldActionPerformed
    Asgn_3_Hello_world shw = new Asgn_3_Hello_world();
    shw.setLocationRelativeTo(null);
    shw.setVisible(true);
    }//GEN-LAST:event_m_btnHelloWorldActionPerformed

    private void m_btnHelloWorldMeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_btnHelloWorldMeActionPerformed
         Asgn_3_Hello_world_Me hwf = new Asgn_3_Hello_world_Me(); //Create Hello World form
    hwf.setLocationRelativeTo(null);                              //Center the Hello World form on screen
    hwf.setVisible(true);                                         //Display the Hello World form
    }//GEN-LAST:event_m_btnHelloWorldMeActionPerformed

    private void btn_PolymorphismActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PolymorphismActionPerformed
        Assignment_11_GUI hwf = new Assignment_11_GUI();
        hwf.setLocationRelativeTo(null);
        hwf.setVisible(true);
    }//GEN-LAST:event_btn_PolymorphismActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Asgn_0_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Asgn_0_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Asgn_0_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Asgn_0_MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Asgn_0_MainMenu().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_1_NumberAddition;
    private javax.swing.JButton btn_Polymorphism;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton m_btnHelloWorld;
    private javax.swing.JButton m_btnHelloWorldMe;
    // End of variables declaration//GEN-END:variables
}
